name: Notify Parent Repo Build

on:
  push:
    branches:
      - main

jobs:
  notify-parent:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Parent Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DO_IT_UPDATE_TOKEN }}
          repository: do-it-ecm/do-it
          event-type: submodule-update
          client-payload: '{"submodule": "${{ github.repository }}"}'
