name: Update Parent Repository

on:
  push:
    branches:
      - main

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger parent repository update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: alouradou/do-it
          event-type: build-parent
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
